import { PageAgentCore } from 'page-agent'
import type { Message } from '@page-agent/llms'
import { PageController } from '@page-agent/page-controller'

import { fetchAIInvoke } from '@/api/ai'
import type { AIBootstrapPayload, AIConfirmPreview, AIInvokeResponse, AIPageId } from '@/types'

interface AgentRuntimeContext {
  pageId: AIPageId
  bootstrap: AIBootstrapPayload
}

let currentInvokeResponse: AIInvokeResponse | null = null

function buildDoneArguments(response: AIInvokeResponse) {
  const extraSections: string[] = []

  if (response.confirmPreview?.previewText) {
    extraSections.push(`预览结果：${response.confirmPreview.previewText}`)
  }

  if (response.warnings?.length) {
    extraSections.push(`注意事项：${response.warnings.join('；')}`)
  }

  const text = [response.assistantMessage, ...extraSections].filter(Boolean).join('\n\n')

  return {
    evaluation_previous_goal: 'Finished answering the user based on current page context.',
    memory: 'The response was generated by the backend AI gateway.',
    next_goal: 'Wait for the next user message.',
    action: {
      done: {
        text,
        success: true,
      },
    },
  }
}

function buildOpenAICompatiblePayload(argumentsPayload: Record<string, unknown>) {
  return {
    id: `chatcmpl_${Date.now()}`,
    object: 'chat.completion',
    created: Math.floor(Date.now() / 1000),
    model: 'smart-fish-page-agent-proxy',
    choices: [
      {
        index: 0,
        finish_reason: 'tool_calls',
        message: {
          role: 'assistant',
          content: null,
          tool_calls: [
            {
              id: `call_${Date.now()}`,
              type: 'function',
              function: {
                name: 'AgentOutput',
                arguments: JSON.stringify(argumentsPayload),
              },
            },
          ],
        },
      },
    ],
    usage: {
      prompt_tokens: 0,
      completion_tokens: 0,
      total_tokens: 0,
    },
  }
}

export async function createPageAgent(context: AgentRuntimeContext) {
  currentInvokeResponse = null

  const customFetch: typeof fetch = async (_input, init) => {
    const body = init?.body ? JSON.parse(String(init.body)) : {}
    const messages = ((body.messages as Message[] | undefined) ?? []).map((message) => ({
      role: message.role,
      content: String(message.content ?? ''),
    }))

    const response = await fetchAIInvoke({
      pageId: context.pageId,
      messages,
      contextVersion: context.bootstrap.pageContextSummary.contextVersion,
      pageContextSummary: context.bootstrap.pageContextSummary as unknown as Record<string, unknown>,
      allowedTools: context.bootstrap.allowedTools,
    })

    currentInvokeResponse = response

    return new Response(JSON.stringify(buildOpenAICompatiblePayload(buildDoneArguments(response))), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  return new PageAgentCore({
    baseURL: '/api/ai/agent/invoke',
    apiKey: 'server-proxied',
    model: 'smart-fish-page-agent-proxy',
    customFetch,
    pageController: new PageController({ enableMask: false }),
    language: 'zh-CN',
    stepDelay: 0,
    maxSteps: 1,
    experimentalScriptExecutionTool: false,
    customTools: {
      execute_javascript: null,
    },
    instructions: {
      system: context.bootstrap.systemInstructions,
      getPageInstructions: () => context.bootstrap.pageInstructions,
    },
  })
}

export function consumeLastInvokeResponse(): AIInvokeResponse | null {
  const result = currentInvokeResponse
  currentInvokeResponse = null
  return result
}

export function createPreviewMessage(preview: AIConfirmPreview): string {
  return `${preview.previewText}\n\n风险等级：${preview.riskLevel}\n确认令牌：${preview.confirmToken}`
}
