import type { AIEnvironmentMode, AIPageId } from '@/types'

export const AI_WELCOME_MESSAGE = '你好！我是智慧渔业小助手，我可结合当前系统状态答疑，替你操作。'

export const AI_MODE_LABEL: Record<AIEnvironmentMode, string> = {
  mock: '模拟模式',
  real: '实时模式'
}

export const AI_PAGE_LABEL: Record<AIPageId, string> = {
  'global-chat': '全局会话',
  'fishery-dashboard': '监测控制台',
  feeding: '精准投喂',
  'water-quality': '水质监测',
  growth: '生长识别'
}

export const AI_WARNING_BLACKLIST = [
  'Response generated by upstream model service.',
  'Current environment mode is'
]
